### ISSUE TITLE
Launcher backend crashes for the new interface of deepin-appstore since 3.0.0

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#209]
```
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: [signal 0xb code=0x1 addr=0x0]
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 42 [running]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 16 [semacquire]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: sync.Wait.pN14_sync.WaitGroup
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/sync/waitgroup.go:132
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 18 [finalizer wait]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: created by runtime_createfing
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/mgc0.c:2572
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 19 [syscall]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine in C code; stack unavailable
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: created by os_signal..import
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/os/signal/signal_unix.go:25
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 21 [IO wait]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.runtime_pollWait
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/netpoll.goc:151
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.Wait.pN12_net.pollDesc
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:84
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.WaitRead.pN12_net.pollDesc
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:89
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.readMsg.pN9_net.netFD
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_unix.go:296
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.ReadMsgUnix.pN12_net.UnixConn
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/unixsock_posix.go:147
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: io.ReadAtLeast
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:298
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: io.ReadFull
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:316
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 22 [chan receive]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 23 [IO wait]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.runtime_pollWait
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/netpoll.goc:151
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.Wait.pN12_net.pollDesc
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:84
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.WaitRead.pN12_net.pollDesc
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:89
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.readMsg.pN9_net.netFD
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_unix.go:296
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.ReadMsgUnix.pN12_net.UnixConn
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/unixsock_posix.go:147
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: io.ReadAtLeast
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:298
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: io.ReadFull
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:316
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 24 [chan receive]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 25 [chan receive]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 26 [chan receive]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 27 [chan send]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 28 [chan send]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 29 [chan receive]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 30 [IO wait]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.runtime_pollWait
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/netpoll.goc:151
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.Wait.pN12_net.pollDesc
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:84
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.WaitRead.pN12_net.pollDesc
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:89
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.Read.pN9_net.netFD
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_unix.go:242
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.Read.pN8_net.conn
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/net.go:121
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.Read.pN12_net.UnixConn
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/unixsock_posix.go:103
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: io.ReadAtLeast
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:298
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: io.ReadFull
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:316
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 31 [chan receive]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 33 [select]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 35 [chan send]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 36 [chan send]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 37 [chan receive]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 38 [IO wait]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.runtime_pollWait
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/netpoll.goc:151
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.Wait.pN12_net.pollDesc
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:84
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.WaitRead.pN12_net.pollDesc
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:89
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.Read.pN9_net.netFD
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_unix.go:242
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.Read.pN8_net.conn
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/net.go:121
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: net.Read.pN12_net.UnixConn
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/unixsock_posix.go:103
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: io.ReadAtLeast
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:298
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: io.ReadFull
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:316
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 39 [chan receive]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 40 [select]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 41 [chan send]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 43 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 44 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 45 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 46 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 47 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 48 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 50 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 51 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 52 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 53 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 54 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 55 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 56 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 57 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 58 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 59 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 60 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 61 [runnable]:
Dec 29 19:52:47 flygon.felixc.at com.deepin.daemon.InputDevices[11159]: goroutine 62 [runnable]:
Dec 29 19:52:47 flygon.felixc.at dbus-daemon[11159]: Activated service 'com.deepin.daemon.InputDevices' failed: Process com.deepin.daemon.InputDevices exited with status 2
```

**Comment by fasheng** [comment]
… :/



2015年12月29日 下午8:04, 下午8:04，在 Felix Yan <notifications@github.com> 已写:

**Comment by fasheng** [comment]
Simple but great patch, it works :+1: 

I will report this to upstream to see if Launcher could run without the latest deepin appstore.

**Comment by oberon2007** [comment]
I'm still having issues with the launcher: It is showing completely empty. :-| 
**deepin-daemon 3.0.1-1** and **deepin-launcher 3.0.1-1**
Also with todays packages every other time the session fails to start and falls back to the greeter.

**Comment by oberon2007** [comment]
The empty launcher issue is fixed for me by downgrading **deepin-daemon** to **2.93.5.20151221-1** while keeping all other pkgs in latest versions.

**Comment by fasheng** [comment]
Well, bad news.

I installed **deepin-lastore-daemon**(http://ur1.ca/od5aq, and a gccgo patch on the way https://cr.deepin.io/#/c/10151) locally and solved the panic issue of dde-session-daemon, but the generated `/var/lib/lastore/desktop_package.json` is empty so there is no launcher items, too.

Even worse is that the guys updates `desktop_package.json` through the trigger of `dpkg`. So it should be a hard job for us to let deepin-lastore-daemon works in arch.

I think of a temporary solution is to follow Bernhard's advice, just use the old launcher code. Here is a patch which owns all the code of launcher under **2.93.5**, just need remove `dde-daemon/launcher` folder before patch it.
http://paste.fedoraproject.org/305896/60339145/raw/

Discuss with upstream is continue...

**Comment by fasheng** [comment]
OK, the latest code of dde-daemon solved the problem now, and the laucnher just works as before :)

**Comment by oberon2007** [comment]
Fixed for me, too! Awesome, thank you! Also for some reason I can clearly notice an improvement in responsiveness with todays update. Cool! :)

**Comment by felixonmars** [comment]
Solved now, thanks :)
