### ISSUE TITLE
Crash in startdde after started for ~20s

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#222]
It actually looks very strange to me, and I am not sure if this helps...

```
Jan 06 20:32:00 flygon.felixc.at systemd-coredump[13676]: Process 6021 (startdde) of user 1000 dumped core.

                                                          Stack trace of thread 6583:
                                                          #0  0x00007f5be3d6ee15 _nv014tls (libnvidia-tls.so.358.16)
                                                          #1  0x00007f5be606c088 n/a (libGL.so.1)
                                                          #2  0x00007f5be60af365 n/a (libGL.so.1)
                                                          #3  0x00007f5beecb5885 n/a (n/a)
```

**Comment by fasheng** [comment]
could you reproduce it? and upload ~/.xsessionerrors please.



2016年1月6日 下午8:44, 下午8:44，在 Felix Yan <notifications@github.com> 已写:

**Comment by felixonmars** [comment]
I cannot reproduce it for now. Interested part in xsession errors:

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x100000000]

goroutine 16 [syscall]:
runtime_dopanic
        /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/panic.c:131
runtime_throw
        /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/panic.c:193
sig_panic_leadin
        /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/go-signal.c:247
sig_panic_info_handler
        /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/go-signal.c:281

        :0

        :0

        :0

        :0

        :0

        :0

        :0

        :0

        :0
runtime_main
        /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/proc.c:626

goroutine 18 [finalizer wait]:
created by runtime_createfing
        /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/mgc0.c:2572

goroutine 19 [chan send]:

goroutine 20 [chan send]:

goroutine 21 [chan receive]:

goroutine 22 [IO wait]:
net.runtime_pollWait
        /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/netpoll.goc:151
net.Wait.pN12_net.pollDesc
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:84
net.WaitRead.pN12_net.pollDesc
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:89
net.Read.pN9_net.netFD
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_unix.go:242
net.Read.pN8_net.conn
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/net.go:121
net.Read.pN12_net.UnixConn
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/unixsock_posix.go:103
io.ReadAtLeast
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:298
io.ReadFull
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:316

goroutine 23 [IO wait]:
net.runtime_pollWait
        /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/netpoll.goc:151
net.Wait.pN12_net.pollDesc
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:84
net.WaitRead.pN12_net.pollDesc
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:89
net.readMsg.pN9_net.netFD
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_unix.go:296
net.ReadMsgUnix.pN12_net.UnixConn
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/unixsock_posix.go:147
io.ReadAtLeast
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:298
io.ReadFull
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:316

goroutine 24 [chan receive]:

goroutine 25 [chan receive]:

goroutine 26 [chan receive]:

goroutine 29 [chan send]:

goroutine 30 [chan send]:

goroutine 31 [chan receive]:

goroutine 33 [IO wait]:
net.runtime_pollWait
        /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/netpoll.goc:151
net.Wait.pN12_net.pollDesc
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:84
net.WaitRead.pN12_net.pollDesc
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:89
net.Read.pN9_net.netFD
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_unix.go:242
net.Read.pN8_net.conn
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/net.go:121
net.Read.pN12_net.UnixConn
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/unixsock_posix.go:103
io.ReadAtLeast
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:298
io.ReadFull
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:316

goroutine 34 [chan send]:

goroutine 35 [chan send]:

goroutine 36 [chan receive]:

goroutine 37 [IO wait]:
net.runtime_pollWait
        /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/netpoll.goc:151
net.Wait.pN12_net.pollDesc
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:84
net.WaitRead.pN12_net.pollDesc
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:89
net.Read.pN9_net.netFD
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_unix.go:242
net.Read.pN8_net.conn
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/net.go:121
net.Read.pN12_net.UnixConn
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/unixsock_posix.go:103
io.ReadAtLeast
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:298
io.ReadFull
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:316

goroutine 38 [IO wait]:
net.runtime_pollWait
        /build/gcc-multilib/src/gcc-5.3.0/libgo/runtime/netpoll.goc:151
net.Wait.pN12_net.pollDesc
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:84
net.WaitRead.pN12_net.pollDesc
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:89
net.readMsg.pN9_net.netFD
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/fd_unix.go:296
net.ReadMsgUnix.pN12_net.UnixConn
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/net/unixsock_posix.go:147
io.ReadAtLeast
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:298
io.ReadFull
        /build/gcc-multilib/src/gcc-5.3.0/libgo/go/io/io.go:316

goroutine 39 [chan receive]:

goroutine 40 [chan receive]:

goroutine 41 [chan receive]:

goroutine 42 [chan receive]:

goroutine 43 [syscall]:
        goroutine in C code; stack unavailable

goroutine 58 [syscall]:
        goroutine in C code; stack unavailable

goroutine 76 [syscall]:
        goroutine in C code; stack unavailable

goroutine 46 [syscall]:
        goroutine in C code; stack unavailable

goroutine 48 [syscall]:
        goroutine in C code; stack unavailable

goroutine 51 [syscall]:
        goroutine in C code; stack unavailable

goroutine 75 [syscall]:
        goroutine in C code; stack unavailable

goroutine 77 [chan receive]:

goroutine 78 [select]:

goroutine 82 [chan send]:
```

**Comment by felixonmars** [comment]
Got the issue again. Seems like some race condition :(

**Comment by felixonmars** [comment]
Still reproducible with startdde 3.0.3 built with latest go-lib 0.4.7, dde-api 3.0.5, dbus-factory 3.0.2, gir-generator 0.9.2.

**Comment by fasheng** [comment]
Strong issue.
Signal 0xb is SEGV means `Invalid memory reference`, so it should be a cgo issue or something releated. But I have no idea how to debug now for it never appeared here :(
